# Generated by Django 5.0 on 2023-12-30 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrowedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
